language: java

jdk:
  - oraclejdk8

before_install:
  - openssl aes-256-cbc -K $encrypted_c3ce839212e9_key -iv $encrypted_c3ce839212e9_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar

after_success:
  - if [ "$TRAVIS_BRANCH" = "develop" ]; then gradle uploadArchives; fi

